version: "3"

networks:
  default:
    external:
      name: code_runner_net

services:
  python-runner:
    image: python-runner-image
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - code-runner-sync:/code_runner:nocopy
    container_name: python-runner
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 512m

  cpp-runner:
    image: cpp-runner-image
    build:
      context: .
      dockerfile: cpp.Dockerfile
    volumes:
      - code-runner-sync:/code_runner:nocopy
    container_name: cpp-runner
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 512m

  java-runner:
    image: java-runner-image
    build:
      context: .
      dockerfile: java.Dockerfile
    volumes:
      - code-runner-sync:/code_runner:nocopy
    container_name: java-runner
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  code-runner-sync:
    external: true
